# Install NGINX webserver +
---
- name: 'Install Nginx webserver'
  hosts: webserver
  become: yes
  tasks:
  - name: 'Install Nginx apt'
    apt:
      name: nginx
      state: latest

  handlers:
  - name: 'restart nginx'
    service:
      name: nginx
      state: restarted


...