#
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

#Configuratie 
(1..2).each do |aantal| # loop 
config.vm.define "webserver-#{aantal}" do |web| #defineer de naam
web.vm.hostname = "nginxServer" #defineer de hostaan
web.vm.box = "ubuntu/trusty64" # defineer systeem
 
#Virtualbox settings
web.vm.provider "virtualbox" do |vb|
  vb.gui = false
  vb.name = "vagrant-web-box#{aantal}"
  vb.memory = "2048"


#//// Deze is niet nodig ivm met ansible commands per klant  
 #Ansbile provisioning
 #web.vm.provision "ansible_local" do |ansible|
 #ansible.playbook = "nginxWeb.yaml" 

end #configure
end # web confgi
end # virtualbox 
end